BINARY := soe_backup
DEPS_INC := soeutil soebind soercsdb soemempools soemsgs soemsgnet soelogger soekvs soemetadbcli soeapi
DEPS_LIB := soeutil soebind soercsdb soemempools soemsgs soemsgnet soelogger soekvs soemetadbcli soeapi

include ../../inc.mk
