BINARY := soemetadbsrv
DEPS_INC := soeutil soebind soercsdb soemempools soemsgs soemsgnet soelogger soemetadbcli
DEPS_LIB := soeutil soebind soercsdb soemempools soemsgs soemsgnet soelogger soemetadbcli


include ../inc.mk
